package com.trc.domain.support.ticket;


public enum TicketCategory {
  	
   ACTIVATION, MRC, TOPUP, BALANCE_MISMATCH, RESET_PASSWORD, REACTIVATE_ACCOUNT, DEACTIVATE_ACCOUNT, 
   SUSPENDED_ACCOUNT, SWAP_DEVICE, REFUND, REVERSE_CREDIT
}
