package com.trc.web.session;

public enum SessionRequest {
  DEVICE_SWAP, DEVICE_RENAME, DEVICE_DEACTIVATE, DEVICE_REACTIVATE, DEVICE_ACCOUNT, DEVICE_ACCESSFEEDATE, DEVICE_ACCOUNTDETAIL, CREDITCARD_UPDATE, ENCRYPTER, REFUND, CREDIT, COUPON
}
