package com.trc.domain.ticket;


public enum TicketCategory {
  	
   ACTIVATE_DEVICE, CREATE_ACCOUNT, REACTIVATE_ACCOUNT, DEACTIVATE_ACCOUNT, SUSPEND_ACCOUNT, RESET_PASSWORD, CHANGE_USERNAME_EMAIL, 
   MONTHLY_ACCESS_FEE, USAGE, SWAP_DEVICE, TOPUP, BALANCE_MISMATCH, COUPON, REFUND, CREDIT, OTHERS
}
