package com.trc.user.activation.logger;

import java.io.Serializable;

public enum ActState implements Serializable {
  ROOT(null), RESERVE_PROFILE(ROOT), INFO_CONTACT(RESERVE_PROFILE), INFO_DEVICE(INFO_CONTACT), INFO_PAYMENT(INFO_CONTACT), ACTIVATE_BILLING_ACCOUNT(
      INFO_PAYMENT), TEST_ACTIVATION(ACTIVATE_BILLING_ACCOUNT), CHECK_COUPON_CONTRACT(TEST_ACTIVATION), APPLY_COUPON_PAYMENT(CHECK_COUPON_CONTRACT), ACTIVATE_PAYMENT(
      CHECK_COUPON_CONTRACT), ACTIVATE_NETWORK_SERVICE(ACTIVATE_PAYMENT), ACTIVATE_CREATE_SERVICE(ACTIVATE_NETWORK_SERVICE), APPLY_CONTRACT(
      ACTIVATE_CREATE_SERVICE), ACTIVATE_ENABLE_USER(APPLY_CONTRACT), ACTIVATE_SAVE_USER(ACTIVATE_ENABLE_USER), NOTIFY_WELCOME(ACTIVATE_SAVE_USER), HAS_COUPON(
      CHECK_COUPON_CONTRACT), IS_COUPON_PAYMENT(HAS_COUPON), HAS_COUPON_PAYMENT(CHECK_COUPON_CONTRACT), HAS_RECURRING_COUPON(CHECK_COUPON_CONTRACT);

  private ActState parent;

  private ActState(ActState parent) {
    this.parent = parent;
  }

  public ActState getParent() {
    return parent;
  }

}